// Shared content for all three design directions.

const PROFILE = {
  name: "Matteo Aldeghi",
  role: "ML Research @ Bayer",
  affiliation: "Bayer Pharmaceuticals · R&D Machine Learning",
  location: "Cambridge, MA",
  email: "aldeghi.ma@gmail.com",
  links: {
    linkedin: "https://www.linkedin.com/in/matteoaldeghi/",
    scholar: "https://scholar.google.com/citations?user=dtoCihgAAAAJ&hl=en",
    github: "https://github.com/matteoaldeghi",
  },
  bio: "I lead R&D Machine Learning Research at Bayer Pharmaceuticals, where I'm responsible for the development and application of ML/AI solutions across the R&D value chain — from target discovery to clinical translation.",
  bioLong: "Previously, Senior Research Scientist at Google Research, Research Scientist at MIT (with Connor Coley), Vector Postdoctoral Fellow at the Vector Institute (with Alán Aspuru-Guzik), and Humboldt Research Fellow at the Max Planck Institute for Biophysical Chemistry. PhD in Computational Biochemistry from the University of Oxford.",
  interests: "I'm interested in how machine learning and AI can accelerate the rate of scientific discovery and improve research productivity in drug discovery and the life sciences.",
};

const RESUME = [
  {
    org: "Bayer Pharmaceuticals",
    role: "Director → Senior Director, Head of Machine Learning Research",
    period: "2023 — Present",
    yearStart: 2023,
    yearEnd: null,
    location: "Cambridge, MA",
    tags: ["Machine Learning", "Drug Discovery & Development", "Leadership"],
    advisor: null,
  },
  {
    org: "Google Research",
    role: "Senior Research Scientist",
    period: "2022 — 2023",
    yearStart: 2022,
    yearEnd: 2023,
    location: "Mountain View, CA",
    tags: ["Machine Learning", "Molecular Design & Chemistry", "Cloud Computing"],
    advisor: null,
  },
  {
    org: "Massachusetts Institute of Technology",
    role: "Research Scientist",
    period: "2021 — 2022",
    yearStart: 2021,
    yearEnd: 2022,
    location: "Cambridge, MA",
    tags: ["Active Learning", "Cheminformatics", "Graph Neural Networks"],
    advisor: "Connor Coley",
  },
  {
    org: "Vector Institute & University of Toronto",
    role: "Postdoctoral Research Fellow",
    period: "2019 — 2021",
    yearStart: 2019,
    yearEnd: 2021,
    location: "Toronto",
    tags: ["Bayesian Optimization", "Materials Discovery", "Autonomous Experimentation"],
    advisor: "Alán Aspuru-Guzik",
  },
  {
    org: "Max Planck Institute for Biophysical Chemistry",
    role: "Postdoctoral Research Fellow",
    period: "2017 — 2019",
    yearStart: 2017,
    yearEnd: 2019,
    location: "Göttingen",
    tags: ["Protein Design", "Molecular Dynamics", "Free Energy Calculations"],
    advisor: "Bert L. de Groot",
  },
  {
    org: "University of Oxford",
    role: "PhD, Computational Biochemistry",
    period: "2012 — 2016",
    yearStart: 2012,
    yearEnd: 2016,
    location: "Oxford",
    tags: ["Drug Design", "Molecular Dynamics", "Free Energy Calculations", "Monte Carlo Simulations"],
    advisor: "Philip C. Biggin",
    kind: "education",
  },
  {
    org: "University College London",
    role: "MSc, Drug Design",
    period: "2011 — 2012",
    yearStart: 2011,
    yearEnd: 2012,
    location: "London",
    tags: ["Cheminformatics"],
    advisor: null,
    kind: "education",
  },
  {
    org: "University of Insubria",
    role: "BSc, Chemistry",
    period: "2007 — 2010",
    yearStart: 2007,
    yearEnd: 2010,
    location: "Como",
    tags: ["Organic Chemistry"],
    advisor: null,
    kind: "education",
  },
];


// All peer-reviewed and conference publications (48 entries).
const PUBLICATIONS = [
  {
    year: 2026,
    title: "Protein language model-based fitness estimates facilitate resistance mutation identification",
    authors: "D. Schwarz, S. Giese, A. Gupta, P.J. Dziubańska-Kusibab, S. Villalba, A. Cherniack, X. Yang, D. Root, G. Karsli-Uzunbas, H. Greulich, F. Siegel, A. Kamburov, E. Nevedomskaya, C. Christ, M. Aldeghi, J. Mortier",
    venue: "ChemRxiv",
    cite: "2026",
    url: "https://chemrxiv.org/doi/full/10.26434/chemrxiv.15000911/v1",
    affiliation: "Bayer",
    tags: ["protein-LM", "drug resistance"],
  },
  {
    year: 2025,
    title: "Machine learning-assisted exploration of multidrug administration regimens for organoid arrays",
    authors: "I. Yakavets*, S. Kheiri*, J. Cruickshank, R.J. Hickman, F. Rakhshani, M. Aldeghi, E.M. Rajaonson, E.W.K. Young, A. Aspuru-Guzik, D.W. Cescon, E. Kumacheva",
    venue: "Science Advances",
    cite: "11, eadt1851, 2025",
    url: "https://www.science.org/doi/full/10.1126/sciadv.adt1851",
    affiliation: "Toronto",
    tags: ["active learning", "oncology"],
  },
  {
    year: 2025,
    title: "Prospective evaluation of structure-based simulations reveal their ability to predict the impact of kinase mutations on inhibitor binding",
    authors: "S. Singh, V. Gapsys, M. Aldeghi, D. Schaller, A.M. Rangwala, J.B. White, J.P. Bluck, J. Scheen, W.G. Glass, J. Guo, S. Hayat, B.L. de Groot, A. Volkamer, C.D. Christ, M.A. Seeliger, J.D. Chodera",
    venue: "Journal of Physical Chemistry B",
    cite: "129(11), 2882–2902, 2025",
    url: "https://pubs.acs.org/doi/abs/10.1021/acs.jpcb.4c07794",
    affiliation: "Max Planck",
    tags: ["molecular dynamics simulations", "kinase inhibitors"],
  },
  {
    year: 2025,
    title: "Anubis: Bayesian optimization with unknown feasibility constraints for scientific experimentation",
    authors: "R.J. Hickman, G. Tom, Y. Zou, M. Aldeghi, A. Aspuru-Guzik",
    venue: "Digital Discovery",
    cite: "4, 2104–2122, 2025",
    url: "https://pubs.rsc.org/en/content/articlelanding/2025/dd/d5dd00018a",
    affiliation: "Toronto",
    tags: ["Bayesian optimization"],
  },
  {
    year: 2025,
    title: "Atlas: A Brain for Self-driving Laboratories",
    authors: "R.J. Hickman, M. Sim, S. Pablo-García, I. Woolhouse, H. Hao, Z. Bao, P. Bannigan, C. Allen, M. Aldeghi, A. Aspuru-Guzik",
    venue: "Digital Discovery",
    cite: "4, 1006–1029, 2025",
    url: "https://pubs.rsc.org/en/content/articlelanding/2025/dd/d4dd00115j",
    affiliation: "Toronto",
    tags: ["autonomous experimentation"],
  },
  {
    year: 2025,
    title: "Practically significant method comparison protocols for machine learning in small molecule drug discovery",
    authors: "J.R. Ash, C. Wognum, R. Rodríguez-Pérez, M. Aldeghi, A.C. Cheng, D. Clevert, O. Engkvist, C. Fang, D.J. Price, J.M. Hughes-Oliver, W.P. Walters",
    venue: "Journal of Chemical Information and Modeling",
    cite: "65(18), 9398–9411, 2025",
    url: "https://pubs.acs.org/doi/10.1021/acs.jcim.5c01609",
    affiliation: "Bayer",
    tags: ["benchmarking"],
  },
  {
    year: 2024,
    title: "A call for an industry-led initiative to critically assess machine learning for real-world drug discovery",
    authors: "C. Wognum, J.R. Ash, M. Aldeghi, R. Rodríguez-Pérez, C. Fang, A.C. Cheng, D.J. Price, D. Clevert, O. Engkvist, W.P. Walters",
    venue: "Nature Machine Intelligence",
    cite: "6, 1120–1121, 2024",
    url: "https://www.nature.com/articles/s42256-024-00911-w",
    affiliation: "Bayer",
    tags: ["benchmarking"],
  },
  {
    year: 2023,
    title: "Olympus, enhanced: benchmarking mixed-parameter and multi-objective optimization in chemistry and materials science",
    authors: "R.J. Hickman, P. Parakh, A. Cheng, Q. Ai, J. Schrier, M. Aldeghi, A. Aspuru-Guzik",
    venue: "ChemRxiv",
    cite: "2023",
    url: "https://chemrxiv.org/engage/chemrxiv/article-details/6464ae0afb40f6b3eebaab70",
    affiliation: "Google",
    tags: ["benchmarking"],
  },
  {
    year: 2023,
    title: "Machine learning models to accelerate the design of polymeric long-acting injectables",
    authors: "P. Bannigan, Z. Bao, R.J. Hickman, M. Aldeghi, F. Häse, A. Aspuru-Guzik, C. Allen",
    venue: "Nature Communications",
    cite: "14, 35, 2023",
    url: "https://www.nature.com/articles/s41467-022-35343-w",
    affiliation: "Toronto",
    tags: ["polymers", "drug delivery"],
  },
  {
    year: 2022,
    title: "Roughness of molecular property landscapes and its impact on modellability",
    authors: "M. Aldeghi, D.E. Graff, N. Frey, J.A. Morrone, E.O. Pyzer-Knapp, K.E. Jordan, C.W. Coley",
    venue: "Journal of Chemical Information and Modeling",
    cite: "62(19), 4660–4671, 2022",
    url: "https://pubs.acs.org/doi/abs/10.1021/acs.jcim.2c00903",
    affiliation: "MIT",
    tags: ["modellability"],
  },
  {
    year: 2022,
    title: "A graph representation of molecular ensembles for polymer property prediction",
    authors: "M. Aldeghi, C.W. Coley",
    venue: "Chemical Science",
    cite: "13, 10486–10498, 2022",
    url: "https://pubs.rsc.org/en/content/articlelanding/2022/SC/D2SC02839E",
    affiliation: "MIT",
    tags: ["graph neural networks", "polymers"],
  },
  {
    year: 2022,
    title: "A focus on simulation and machine learning as complementary tools for chemical space navigation",
    authors: "M. Aldeghi, C.W. Coley",
    venue: "Chemical Science",
    cite: "13, 8221–8223, 2022",
    url: "https://pubs.rsc.org/en/content/articlelanding/2022/SC/D2SC90130G",
    affiliation: "MIT",
    tags: ["editorial"],
  },
  {
    year: 2022,
    title: "Self-focusing virtual screening with active design space pruning",
    authors: "D.E. Graff, M. Aldeghi, J.A. Morrone, K.E. Jordan, E.O. Pyzer-Knapp, C.W. Coley",
    venue: "Journal of Chemical Information and Modeling",
    cite: "62(16), 3854–3862, 2022",
    url: "https://pubs.acs.org/doi/10.1021/acs.jcim.2c00554",
    affiliation: "MIT",
    tags: ["virtual screening"],
  },
  {
    year: 2022,
    title: "On scientific understanding with artificial intelligence",
    authors: "M. Krenn, R. Pollice, S.Y. Guo, M. Aldeghi, A. Cervera-Lierta, P. Friederich, G.P. Gomes, F. Häse, A. Jinich, A. Nigam, Z. Yao, A. Aspuru-Guzik",
    venue: "Nature Reviews Physics",
    cite: "2022",
    url: "https://www.nature.com/articles/s42254-022-00518-3",
    affiliation: "Toronto",
    tags: ["AI for science"],
  },
  {
    year: 2022,
    title: "Bayesian optimization with known experimental and design constraints for chemistry applications",
    authors: "R.J. Hickman*, M. Aldeghi*, F. Häse, A. Aspuru-Guzik",
    venue: "Digital Discovery",
    cite: "1, 732–744, 2022",
    url: "https://pubs.rsc.org/en/content/articlelanding/2022/DD/D2DD00028H",
    affiliation: "Toronto",
    tags: ["constrained optimization"],
  },
  {
    year: 2021,
    title: "Self-driving platform for metal nanoparticle synthesis: combining microfluidics and machine learning",
    authors: "H. Tao, T. Wu, S. Kheiri, M. Aldeghi, A. Aspuru-Guzik, E. Kumacheva",
    venue: "Advanced Functional Materials",
    cite: "2106725, 2021",
    url: "https://onlinelibrary.wiley.com/doi/10.1002/adfm.202106725",
    affiliation: "Toronto",
    tags: ["self-driving labs", "nanoparticles"],
  },
  {
    year: 2021,
    title: "Nanoparticle synthesis assisted by machine learning",
    authors: "H. Tao, T. Wu, M. Aldeghi, T.C. Wu, A. Aspuru-Guzik, E. Kumacheva",
    venue: "Nature Reviews Materials",
    cite: "6, 701–716, 2021",
    url: "https://www.nature.com/articles/s41578-021-00337-5",
    affiliation: "Toronto",
    tags: ["nanoparticles", "review"],
  },
  {
    year: 2021,
    title: "Alchemical absolute protein-ligand binding free energies for drug design",
    authors: "Y. Khalak, G. Tresadern, M. Aldeghi, H.M. Baumann, D.L. Mobley, B.L. de Groot, V. Gapsys",
    venue: "Chemical Science",
    cite: "12, 13958–13971, 2021",
    url: "https://pubs.rsc.org/en/content/articlelanding/2021/SC/D1SC03472C",
    affiliation: "Max Planck",
    tags: ["binding free energy"],
  },
  {
    year: 2021,
    title: "Gryffin: An algorithm for Bayesian optimization of categorical variables informed by expert knowledge",
    authors: "F. Häse, M. Aldeghi, R.J. Hickman, L.M. Roch, A. Aspuru-Guzik",
    venue: "Applied Physics Reviews",
    cite: "8, 031406, 2021",
    url: "https://aip.scitation.org/doi/10.1063/5.0048164",
    affiliation: "Toronto",
    tags: ["categorical optimization"],
  },
  {
    year: 2021,
    title: "Machine learning directed drug formulation development",
    authors: "P. Bannigan, M. Aldeghi, Z. Bao, F. Häse, A. Aspuru-Guzik, C. Allen",
    venue: "Advanced Drug Delivery Reviews",
    cite: "175, 113806, 2021",
    url: "https://www.sciencedirect.com/science/article/abs/pii/S0169409X21001800",
    affiliation: "Toronto",
    tags: ["drug formulation"],
  },
  {
    year: 2021,
    title: "Accurate absolute free energies for ligand–protein binding based on non-equilibrium approaches",
    authors: "V. Gapsys, A. Yildirim, M. Aldeghi, Y. Khalak, D. van der Spoel, B.L. de Groot",
    venue: "Communications Chemistry",
    cite: "4(61), 1–13, 2021",
    url: "https://www.nature.com/articles/s42004-021-00498-y",
    affiliation: "Max Planck",
    tags: ["non-equilibrium simulations"],
  },
  {
    year: 2021,
    title: "Golem: An algorithm for robust experiment and process optimization",
    authors: "M. Aldeghi, F. Häse, R.J. Hickman, I. Tamblyn, A. Aspuru-Guzik",
    venue: "Chemical Science",
    cite: "12, 14792–14807, 2021",
    url: "https://pubs.rsc.org/en/Content/ArticleLanding/2021/SC/D1SC01545A",
    affiliation: "Toronto",
    tags: ["robust optimization"],
  },
  {
    year: 2021,
    title: "Assigning Confidence to Molecular Property Prediction",
    authors: "A. Nigam, R. Pollice, M.F.D. Hurley, R.J. Hickman, M. Aldeghi, N. Yoshikawa, S. Chithrananda, V.A. Voelz, A. Aspuru-Guzik",
    venue: "Expert Opinion on Drug Discovery",
    cite: "16(9), 1009–1023, 2021",
    url: "https://www.tandfonline.com/doi/abs/10.1080/17460441.2021.1925247",
    affiliation: "Toronto",
    tags: ["uncertainty"],
  },
  {
    year: 2021,
    title: "Data-driven strategies for accelerated materials design",
    authors: "R. Pollice, G.P. Gomes, M. Aldeghi, R.J. Hickman, M. Krenn, C. Lavigne, M.L. D'Addario, A. Nigam, C.T. Ser, Z. Yao, A. Aspuru-Guzik",
    venue: "Accounts of Chemical Research",
    cite: "54(4), 849–860, 2021",
    url: "https://pubs.acs.org/doi/10.1021/acs.accounts.0c00785",
    affiliation: "Toronto",
    tags: ["materials"],
  },
  {
    year: 2021,
    title: "Olympus: a benchmarking framework for noisy optimization and experiment planning",
    authors: "F. Häse*, M. Aldeghi*, R.J. Hickman, L.M. Roch, M. Christensen, E. Liles, J.E. Hein, A. Aspuru-Guzik",
    venue: "Machine Learning: Science and Technology",
    cite: "2, 035021, 2021",
    url: "https://iopscience.iop.org/article/10.1088/2632-2153/abedc8/meta",
    affiliation: "Toronto",
    tags: ["benchmarking"],
  },
  {
    year: 2020,
    title: "Structural basis for antibiotic action of the B1 antivitamin 2′-methoxy-thiamine",
    authors: "F.R. von Pappenheim*, M. Aldeghi*, B. Shome, T. Begley, B.L. de Groot, K. Tittmann",
    venue: "Nature Chemical Biology",
    cite: "16, 1237–1245, 2020",
    url: "https://www.nature.com/articles/s41589-020-0628-4",
    affiliation: "Max Planck",
    tags: ["antibiotics", "molecular dynamics simulations"],
  },
  {
    year: 2020,
    title: "Characterising inter-helical interactions of G protein-coupled receptors with the fragment molecular orbital method",
    authors: "A. Heifetz, I. Morao, M.M. Babu, T. James, M.W.Y. Southey, D.G. Fedorov, M. Aldeghi, M.J. Bodkin, A. Townsend-Nicholson",
    venue: "Journal of Chemical Theory and Computation",
    cite: "16(4), 2814–2824, 2020",
    url: "https://pubs.acs.org/doi/abs/10.1021/acs.jctc.9b01136",
    affiliation: "Max Planck",
    tags: ["GPCRs", "QM"],
  },
  {
    year: 2020,
    title: "Large scale relative protein ligand binding affinities using non-equilibrium alchemy",
    authors: "V. Gapsys, L. Pérez-Benito, M. Aldeghi, D. Seeliger, H. Van Vlijmen, G. Tresdern, B.L. de Groot",
    venue: "Chemical Science",
    cite: "11, 1140–1152, 2020",
    url: "https://pubs.rsc.org/en/Content/ArticleLanding/2020/SC/C9SC03754C",
    affiliation: "Max Planck",
    tags: ["drug design", "free energy calculations"],
  },
  {
    year: 2020,
    title: "The SAMPL6 SAMPLing challenge: Assessing the reliability and efficiency of binding free energy calculations",
    authors: "A. Rizzi, T. Jensen, D.R. Slochower, M. Aldeghi, V. Gapsys, D. Ntekoumes, S. Bosisio, M. Papadourakis, N.M. Henriksen, B.L. de Groot, Z. Cournia, A. Dickson, J. Michel, M.K. Gilson, M.R. Shirts, D.L. Mobley, J.D. Chodera",
    venue: "Journal of Computer-Aided Molecular Design",
    cite: "34, 601–633, 2020",
    url: "https://link.springer.com/article/10.1007/s10822-020-00290-5",
    affiliation: "Max Planck",
    tags: ["benchmarking", "binding free energy"],
  },
  {
    year: 2019,
    title: "Predicting kinase inhibitor resistance: physics-based and data-driven approaches",
    authors: "M. Aldeghi, V. Gapsys, B.L. de Groot",
    venue: "ACS Central Science",
    cite: "5(8), 1468–1474, 2019",
    url: "https://pubs.acs.org/doi/abs/10.1021/acscentsci.9b00590",
    affiliation: "Max Planck",
    tags: ["inhibitor resistance", "kinase"],
  },
  {
    year: 2019,
    title: "A molecular mechanism for transthyretin amyloidogenesis",
    authors: "A.W. Yee*, M. Aldeghi*, M. Blakeley, A. Ostermann, P. Mas, M. Moulin, D. de Sanctis, M.W. Bowler, C. Mueller-Dieckmann, E. Mitchell, M. Haertlein, B.L. de Groot, E. Boeri Erba, V.T. Forsyth",
    venue: "Nature Communications",
    cite: "10, 925, 2019",
    url: "https://www.nature.com/articles/s41467-019-08609-z",
    affiliation: "Max Planck",
    tags: ["amyloidogenesis", "molecular simulations"],
  },
  {
    year: 2019,
    title: "Characterising GPCR–ligand interactions using a fragment molecular orbital-based approach",
    authors: "A. Heifetz, T. James, M. Southey, I. Morao, M. Aldeghi, L. Sarrat, D.G. Fedorov, M.J. Bodkin, A. Townsend-Nicholson",
    venue: "Current Opinion in Structural Biology",
    cite: "55, 85–92, 2019",
    url: "https://www.sciencedirect.com/science/article/abs/pii/S0959440X18301702",
    affiliation: "Max Planck",
    tags: ["GPCRs", "QM"],
  },
  {
    year: 2019,
    title: "Accurate calculation of free energy changes upon amino acid mutation",
    authors: "M. Aldeghi, B.L. de Groot, V. Gapsys",
    venue: "Methods in Molecular Biology",
    cite: "1851, 19–47, 2019",
    url: "https://link.springer.com/protocol/10.1007/978-1-4939-8736-8_2",
    affiliation: "Max Planck",
    tags: ["free energy calculations", "review"],
  },
  {
    year: 2018,
    title: "Accurate estimation of ligand binding affinity changes upon protein mutation",
    authors: "M. Aldeghi, V. Gapsys, B.L. de Groot",
    venue: "ACS Central Science",
    cite: "4(12), 1708–1718, 2018",
    url: "https://pubs.acs.org/doi/10.1021/acscentsci.8b00717",
    affiliation: "Max Planck",
    tags: ["protein mutation", "free energy calculations"],
  },
  {
    year: 2018,
    title: "Absolute alchemical free energy calculations for ligand binding: a beginner's guide",
    authors: "M. Aldeghi, J.P. Bluck, P.C. Biggin",
    venue: "Methods in Molecular Biology",
    cite: "1762, 199–232, 2018",
    url: "https://link.springer.com/protocol/10.1007%2F978-1-4939-7756-7_11",
    affiliation: "Oxford",
    tags: ["review", "free energy calculations"],
  },
  {
    year: 2018,
    title: "Large-scale analysis of water stability in bromodomain binding pockets with grand canonical Monte Carlo",
    authors: "M. Aldeghi, G.A. Ross, M.J. Bodkin, J.W. Essex, S. Knapp, P.C. Biggin",
    venue: "Communications Chemistry",
    cite: "1, 19, 2018",
    url: "https://www.nature.com/articles/s42004-018-0019-x",
    affiliation: "Oxford",
    tags: ["Monte Carlo", "bromodomains"],
  },
  {
    year: 2018,
    title: "Exploring GPCR-ligand interactions with the Fragment Molecular Orbital (FMO) method",
    authors: "E.I. Chudyk, L. Sarrat, M. Aldeghi, D.G. Fedorov, M.J. Bodkin, T. James, M. Southey, R. Robinson, I. Morao, A. Heifetz",
    venue: "Methods in Molecular Biology",
    cite: "1705, 179–195, 2018",
    url: "https://link.springer.com/protocol/10.1007/978-1-4939-7465-8_8",
    affiliation: "Oxford",
    tags: ["GPCRs", "QM"],
  },
  {
    year: 2017,
    title: "Statistical analysis on the performance of Molecular Mechanics Poisson-Boltzmann Surface Area versus absolute binding free energy calculations: bromodomains as a case study",
    authors: "M. Aldeghi, M.J. Bodkin, S. Knapp, P.C. Biggin",
    venue: "Journal of Chemical Information and Modeling",
    cite: "57(9), 2203–2221, 2017",
    url: "http://pubs.acs.org/doi/10.1021/acs.jcim.7b00347",
    affiliation: "Oxford",
    tags: ["MM-PBSA", "binding free energy"],
  },
  {
    year: 2017,
    title: "Advances in molecular simulation",
    authors: "M. Aldeghi, P.C. Biggin",
    venue: "Comprehensive Medicinal Chemistry III",
    cite: "3, Ch. 2, 14–33, 2017",
    url: "https://www.researchgate.net/publication/311313651_Advances_in_Molecular_Simulation",
    affiliation: "Oxford",
    tags: ["review", "MD"],
  },
  {
    year: 2017,
    title: "Predictions of ligand selectivity from absolute binding free energy calculations",
    authors: "M. Aldeghi, A. Heifetz, M.J. Bodkin, S. Knapp, P.C. Biggin",
    venue: "Journal of the American Chemical Society",
    cite: "139(2), 946–957, 2017",
    url: "http://pubs.acs.org/doi/abs/10.1021/jacs.6b11467",
    affiliation: "Oxford",
    tags: ["binding free energy"],
  },
  {
    year: 2016,
    title: "Using the fragment molecular orbital method to investigate agonist–orexin-2 receptor interactions",
    authors: "A. Heifetz, M. Aldeghi, E.I. Chudyk, D.G. Fedorov, M.J. Bodkin, P.C. Biggin",
    venue: "Biochemical Society Transactions",
    cite: "44(2), 574–581, 2016",
    url: "http://www.biochemsoctrans.org/content/44/2/574",
    affiliation: "Oxford",
    tags: ["GPCRs", "QM"],
  },
  {
    year: 2016,
    title: "Fragment molecular orbital method applied to lead optimization of novel Interleukin-2 Inducible T-Cell Kinase (ITK) inhibitors",
    authors: "A. Heifetz, G. Trani, M. Aldeghi, C.H. MacKinnon, P.A. McEwan, F.A. Brookfield, E.I. Chudyk, M.J. Bodkin, Z. Pei, J.D. Burch, D.F. Ortwine",
    venue: "Journal of Medicinal Chemistry",
    cite: "59(9), 4352–4363, 2016",
    url: "http://pubs.acs.org/doi/abs/10.1021/acs.jmedchem.6b00045",
    affiliation: "Oxford",
    tags: ["lead optimization", "kinase"],
  },
  {
    year: 2016,
    title: "Application of an integrated GPCR SAR-Modelling platform to explain the activation selectivity of human 5-HT2C over 5-HT2B",
    authors: "A. Heifetz, R.I. Storer, G. McMurray, T. James, I. Morao, M. Aldeghi, M.J. Bodkin, P.C. Biggin",
    venue: "ACS Chemical Biology",
    cite: "11(5), 1372–1382, 2016",
    url: "http://pubs.acs.org/doi/abs/10.1021/acschembio.5b01045",
    affiliation: "Oxford",
    tags: ["GPCRs", "QM"],
  },
  {
    year: 2016,
    title: "Beyond membrane protein structure: drug discovery, dynamics and difficulties",
    authors: "P.C. Biggin, M. Aldeghi, M.J. Bodkin, A. Heifetz",
    venue: "Advances in Experimental Medicine and Biology",
    cite: "Ch. 11, 450–461, 2016",
    url: "http://link.springer.com/chapter/10.1007%2F978-3-319-35072-1_12",
    affiliation: "Oxford",
    tags: ["membrane proteins", "review"],
  },
  {
    year: 2016,
    title: "Accurate calculation of the absolute free energy of binding for drug molecules",
    authors: "M. Aldeghi, A. Heifetz, M.J. Bodkin, S. Knapp, P.C. Biggin",
    venue: "Chemical Science",
    cite: "7, 207–218, 2016",
    url: "http://pubs.rsc.org/en/content/articlelanding/2015/sc/c5sc02678d",
    affiliation: "Oxford",
    tags: ["binding free energy"],
  },
  {
    year: 2015,
    title: "The Fragment Molecular Orbital method reveals new insight into the chemical nature of GPCR-ligand interactions",
    authors: "A. Heifetz, E.I. Chudyk, L. Gleave, M. Aldeghi, V. Cherezov, D.G. Fedorov, P.C. Biggin, M.J. Bodkin",
    venue: "Journal of Chemical Information and Modeling",
    cite: "56(1), 159–172, 2015",
    url: "http://pubs.acs.org/doi/10.1021/acs.jcim.5b00644",
    affiliation: "Oxford",
    tags: ["GPCRs", "QM"],
  },
  {
    year: 2015,
    title: "Selective targeting of the BRG/PB1 bromodomains impairs embryonic and trophoblast stem cell maintenance",
    authors: "O. Fedorov, J. Castex, C. Tallant, D.R. Owen, S. Martin, M. Aldeghi, O. Monteiro, P. Filippakopoulos, S. Picaud, J.D. Trzupek, B.S. Gerstenberger, C. Bountra, D. Willmann, C. Wells, M. Philpott, C. Rogers, P.C. Biggin, P.E. Brennan, M.E. Bunnage, R. Schüle, T. Günther, S. Knapp, S. Müller",
    venue: "Science Advances",
    cite: "1, e1500723, 2015",
    url: "http://advances.sciencemag.org/content/1/10/e1500723",
    affiliation: "Oxford",
    tags: ["bromodomains"],
  },
  {
    year: 2014,
    title: "Two and Three-dimensional Rings in Drugs",
    authors: "M. Aldeghi, S. Malhotra, D.L. Selwood, A.W.E. Chan",
    venue: "Chemical Biology & Drug Design",
    cite: "83, 450–461, 2014",
    url: "http://dx.doi.org/10.1111/cbdd.12260",
    affiliation: "UCL",
    tags: ["cheminformatics", "med chem"],
  },
];

// Research themes (cards on the home page)
const RESEARCH = [
  {
    id: "props",
    title: "Molecular property prediction",
    blurb: "Predicting protein–ligand binding affinity, mutation effects, and polymer properties with ML and physics-based methods.",
    image: "images/research/mutation.png",
    keywords: ["GNNs", "alchemy", "polymers", "kinases"],
  },
  {
    id: "active",
    title: "Active learning & experiment design",
    blurb: "Algorithms and software for model-guided optimization — categorical, constrained, and robust — coupled to autonomous laboratories.",
    image: "images/research/ml-and-exp-design.png",
    keywords: ["Bayesian opt.", "self-driving labs", "constraints"],
  },
  {
    id: "mech",
    title: "Biomolecular mechanism & dynamics",
    blurb: "Atomistic simulations to study water-mediated binding, amyloidogenesis, and antibiotic action of antivitamins.",
    image: "images/research/protein-ligand.png",
    keywords: ["MD", "Monte Carlo", "thermodynamics"],
  },
];

// Career summary stats
const STATS = [
  { value: "40+", label: "Peer-reviewed publications" },
  { value: "12y", label: "Computational chemistry & ML" },
  { value: "8", label: "Open-source projects" },
  { value: "5", label: "Research institutions" },
];

window.PROFILE = PROFILE;
window.RESUME = RESUME;
window.PUBLICATIONS = PUBLICATIONS;
window.RESEARCH = RESEARCH;
window.STATS = STATS;
